# Generated by Django 5.0.7 on 2024-07-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "email",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Non-binary", "Non-binary"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("birth_date", models.DateField()),
                ("language", models.CharField(default="", max_length=20)),
                ("manager", models.BooleanField()),
                ("join_date", models.DateTimeField(auto_now_add=True)),
                ("recent_login_date", models.DateTimeField(auto_now_add=True)),
                ("privacy_agree", models.BooleanField()),
                ("marketing_agree", models.BooleanField()),
                ("nickname", models.CharField(default="", max_length=20)),
                ("active", models.BooleanField()),
                ("avaturn_user_id", models.CharField(max_length=200, null=True)),
                ("avatar_agree", models.BooleanField()),
                ("fcm_token", models.CharField(max_length=256, null=True)),
                ("info_update_date", models.DateTimeField(null=True)),
            ],
        ),
    ]
